name: CI
on:
  push:
    branches: ["develop"]
env:
  STATE_RELEASE_VERSION: 1.1.0
jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout

      - name: Update theme
        run: git submodule update --init --recursive

      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: "0.99.1"

      - name: Build Html Website
        run: hugo -D

      - name: Test Html Build with HTMLPROOFER
        uses: chabad360/htmlproofer@v1.1
        with:
          directory: "./public"
          arguments: --allow-missing-href --disable-external --empty-alt-ignore

      - name: Steps for password file
        run: echo "${{ secrets.USERS_PASSWORDS }}" >> createPassUser.txt

      - name: Login to gcloud registry
        id: gcloud
        uses: elgohr/gcloud-login-action@v1
        with:
          account_key: ${{ secrets.GCLOUD_KEY }}

      - name: Steps for password file
        run: echo "${{ steps.gcloud.outputs.username }}"

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        env:
          USER: ${{ secrets.HTPASSWD_USER }}
          PASSWORD: ${{ secrets.HTPASSWD_PASSWORD }}
        with:
          name: week8-355318/week-4
          username: ${{ steps.gcloud.outputs.username }}
          password: ${{ steps.gcloud.outputs.password }}
          registry: gcr.io, us.gcr.io, eu.gcr.io or asia.gcr.io
          tags: "latest,${{ env.STATE_RELEASE_VERSION }}"
          dockerfile: ./docker-resources/Dockerfile
          buildargs: USER,PASSWORD

      - uses: repo-sync/pull-request@v2
        name: pull-request
        with:
          destination_branch: "main"
          pr_title: "Pulling ${{ github.ref }} into main"
          pr_body: "👑 *An automated PR*"
          pr_reviewer: "mdeleon"
          pr_draft: true
          github_token: ${{ secrets.TOKEN_REPOSITORY }}
